site_name: CTCSpeechRecognition
theme : simplex
repo_url : https://github.com/SeanNaren/CTCSpeechRecognition
use_directory_urls : false
markdown_extensions: [extra]
docs_dir : doc
pages:
- [index.md, Home]
- [Network.md, Network]
- [DeepSpeechModel.md, DeepSpeechModel]
- [Mapper.md, Mapper]
- [Evaluator.md, Evaluator]
- [ModelEvaluator.md, ModelEvaluator]
- [Utils.md, Utils]
- [UtilsMultiGPU.md, UtilsMultiGPU]
- [Loader.md, Loader]